[package]
name = "rtcmlib"
version = "0.1.0"
edition = "2021"

[dependencies]
hifitime = "4.0.0-beta"
log = "0.4.22"
rinex = { git = "https://github.com/georust/rinex", features=["full"]}
rtcm-rs = "0.11.0"
